name: Bug Report
description: Create a report to help us reproduce and fix the bug

body:
  - type: markdown
    attributes:
      value: >
        #### Before submitting a bug, please make sure the issue hasn't been already addressed by searching through [the existing and past issues](https://github.com/MartinBraquet/task-allocation-auctions/issues?q=is%3Aissue+sort%3Acreated-desc+).
  - type: textarea
    id: system-info
    attributes:
      label: System Info
      description: |
        Please share your system info with us.

      value: >
        OS version:
        Python / Matlab version:
        The current version of `gcaa` being used (if python):
    validations:
      required: true

  - type: textarea
    attributes:
      label: Describe the bug
      description: |
        Please provide a clear and concise description of what the bug is.

        If relevant, add a minimal example so that we can reproduce the error by running the code. 
        It is very important for the snippet to be as succinct (minimal) as possible, so please take time to trim 
        down any irrelevant code to help us debug efficiently.

        Please also paste or describe the results you observe instead of the expected results. 
        If you observe an error, please paste the error message including the **full** traceback of the exception. 
        It may be relevant to wrap error messages in ```` ```triple quotes blocks``` ````.
      placeholder: |
        A clear and concise description of what the bug is.

        ```python
        Sample code to reproduce the problem
        ```

        ```
        The error message you got, with the full traceback.
        ````
    validations:
      required: true
  - type: markdown
    attributes:
      value: >
        Thanks for contributing!
